spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

seed:
  file:
    path: classpath:seed-data.json

security:
  jwt:
    secret: MY_SUPER_SECRET_KEY_WHICH_IS_DEFINITELY_MORE_THAN_32_CHARACTERS_LONG
    expiration: 86400000

auth:
  max-attempts: 3
  block-duration-minutes: 5

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info
  endpoint:
    health:
      show-details: always