spring:
  datasource:
    url: jdbc:postgresql://stg-server:5432/GYM-CRM-stg
    username: postgres
    password: stgpassword
    driver-class-name: org.postgresql.Driver

cors:
  allowed-origins: https://prod-domain.com
  allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS