spring:
  datasource:
    url: jdbc:postgresql://dev-server:5432/GYM-CRM-dev
    username: postgres
    password: devpassword
    driver-class-name: org.postgresql.Driver

cors:
  allowed-origins: http://dev-server:3000
  allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS