eureka:
  client:
    enabled: false

spring:
  cloud:
    discovery:
      enabled: false
  jms:
    listener:
      auto-startup: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8083/oauth2/jwks   # won't be called with no real traffic
          issuer-uri: http://localhost:8083