server:
  port: 8081

spring:
  application:
    name: workload-service
  security:
      oauth2:
        resourceserver:
          jwt:
            # Workload fetches RSA public key from here once and caches it
            jwk-set-uri: http://localhost:8083/oauth2/jwks
            # Must exactly match app.auth.issuer-uri in auth service
            issuer-uri: http://localhost:8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  pattern:
    level: "%5p [txId=%X{txId}]"