server:
  port: 8081

spring:
  application:
    name: workload-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service/oauth2/jwks
          issuer-uri: http://localhost:8083
  activemq:
    broker-url: tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=6&jms.redeliveryPolicy.redeliveryDelay=1000
    user: admin
    password: admin

  jms:
    listener:
      auto-startup: true

activemq:
  queue:
    workload: gym.workload.queue

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  pattern:
    level: "%5p [txId=%X{transactionId:-SYSTEM}]"